### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by tbergen1** [hewhodevs/jamming#2]
### Criteria 1: Objective
* **Score Level**: 4/4 (Exceeds Expectations)
* *Comment(s)*:  Your objective is a good one.  Giving a way to avoid duplicates within your playlists is a good UX paradigm.

### Criteria 2: Background
* **Score Level**: 4/4 (Exceeds Expectations)
* *Comment(s)*: Your background section is good!  It provides a detailed explanation of the pain point this feature is addressing.  You also gave a good summary of the overall functionality of the feature within the app.  Nice work!

### Criteria 3: Technical Design
* **Score Level**: 4/4 (Exceeds Expectations)
* *Comment(s)*: You did a great job on your technical design section.  It is thorough and provides all of the details required to implement the feature properly.  Great work!

### Criteria 4: Caveats
* **Score Level**: 4/4 (Exceeds Expectations)
* *Comment(s)*: You did a great job thinking about the caveats of this feature.  You are right to be concerned with performance issues when working with larger data sets, so it is great to see that you considered this possibility.

### Overall Score: 16/16
Overall, you did a great job with this feature request.  You chose a feature that would greatly improve the UX of the app and explained the necessity for this feature clearly and concisely.  You also did well in detailing the specific aspects of the technical implementation and what caveats you might encounter with your initial implementation.  Great work!

**Comment by hewhodevs** [comment]
Thanks Tom for the prompt review. Much appreciated!
